featurisation:
  method: aqme
  output_features_path: data/features/aqme_descriptors.csv
  smiles_path: data/smiles.csv
  smiles_column: smiles
  id_column: substrate_id

  parameters:
    conformer_generation: rdkit
    optimiser: xtb
  
output:
  aqme_output_dir: outputs/aqme/