featurisation:
  smiles_path: data/smiles.csv
  smiles_column: smiles
  id_column: substrate_id
  method: mordred
  output_features_path: data/features/mordred_descriptors.csv

  parameters:
    missingVal: np.NaN  # Value to use for missing data
    ignore_3D: true    # Only use 2D descriptors