featurisation:
  smiles_path: data/smiles.csv
  smiles_column: smiles
  id_column: substrate_id
  method: morgan
  output_features_path: data/features/morgan_fingerprints.csv

  parameters:
    radius: 2
    n_bits: 2048