data:
  yield_path: data/exp_data_processed.csv
  features_dir: data/features/

preprocessing:
  join_key: substrate_id
  join_type: inner
  duplicate_selection: first
  desc_labels: True

  remove_nan_columns: True
  nan_removal_method: all

  remove_no_variance_columns: True