data:
  model_input_dir: data/model_input/

training:
  columns_to_remove:
    - substrate_id
  target_variables: 
    yield
  
  test_size: 0.2
  cv_folds: 5
  random_state: 42
  scoring_strategy: null


model:
  model_dir: src/models/architectures/

output:
  output_model_dir: outputs/trained_models/


