data:
  yield_path: data/exp_data.csv
  features_dir: data/features/
  model_input_dir: data/model_input/
  

featurisation:
  smiles_path: data/smiles.csv
  smiles_column: smiles
  id_column: substrate_id
  method: null
  output_features_path: null
  parameters:

    radius: 2
    n_bits: 2048
    
    descriptors: null  # null = all descriptors
    ignore_3d: true    # Only use 2D descriptors
    timeout: 10        # Max time in seconds per molecule
    
    missingVal: np.NaN
    silent: True

    n_jobs: -1


preprocessing:
  melt: True
  encode: True
  join_key: substrate_id
  join_type: inner
  duplicate_selection: first
  missing_strategy: drop
  feature_columns: null


training:
  test_size: 0.2
  cv_folds: 5
  random_state: 42
  scoring_strategy: custom


model:
  type: null


logging:
  save_logs: true
  log_level: INFO
  log_dir: logs/


output:
  save_model: true
  model_dir: models/
  results_dir: results/
