data:
  yield_path: data/exp_data.csv
  features_dir: data/features/
  model_input_dir: data/model_input/
  exp_optimum_csv_path: data/metrics/exp_optimum_regions.csv
  

featurisation:
  smiles_path: data/smiles.csv
  smiles_column: smiles
  id_column: substrate_id
  mol_column: mol
  method: null
  output_features_path: null
  parameters:

    # Morgan Fingerprints
    radius: 2
    n_bits: 2048
    
    # RDKit descriptors
    descriptors: null
    ignore_3d: true
    timeout: 10
    
    missingVal: np.NaN
    silent: True

    # AQME
    conformer_generation: rdkit
    optimiser: xtb

    n_jobs: -1

  # AQME specific featurisation
  aqme_desc_path: null
  chosen_descriptor: null
  choice_method: null  # or min


preprocessing:
  melt: True
  encode: True
  join_key: substrate_id
  join_type: inner
  duplicate_selection: first
  missing_strategy: drop
  feature_columns: null
  var_name: null
  value_name: null
  drop_nan: True
  one_hot_encode_columns:
    - reagent
  # - extend if mulitple columns need to be one-hot encoded


training:
  columns_to_remove: null
  target_variables: null
  random_state: 42


validation:
  id_col: substrate_id
  val_method: null
  indep_vars: null
  dep_vars: null
  constant_vars: null
  standard: true
  custom: true
  test_size: null
  cv_folds: 5
  shuffle: false
  random_state: null
  remove_nan: true
  remove_how: all  # 'all' or 'any'


model:
  type: null
  model_dir: src/models/architectures/
  model_config_dir: configs/models/
  model_output_dir: output/trained_models/


metrics:
  threshold: 0.9
  iter_step: 0.1
  success_cutoff: 10 # minimim value for optimum to be considered. Set to null to disable
  output_dir: null
  log_path: null
  save: false


logging:
  save_logs: true
  log_level: INFO


output:
  model_path: null
  metrics_dir: outputs/metrics/validation_results/
  feature_importance_path: null
  predictions_path: null
  val_log_path: outputs/metrics/validation_log.csv
  aqme_output_dir: outputs/aqme/
